### ISSUE TITLE
installation has a Cython compilation error in ont-remora

### ISSUE THREAD

**Issue by bettingr** [nanoporetech/bonito#356]
My `pip install ont-bonito` within a freshly-installed Python 3.9 miniconda environment ends with a Cython compilation error in `ont-remora`:

```
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          int kmer_len
      ):
          cdef int idx = 0
          cdef int kmer_pos
          for kmer_pos in range(kmer_len):
              idx += int_kmer[kmer_len - kmer_pos - 1] * (4 ** kmer_pos)
              ^
      ------------------------------------------------------------
      
      src/remora/refine_signal_map_core.pyx:83:8: Cannot assign type 'double' to 'int'
``` 

I've attached the full output of the pip command as a text file:
[bonitoCythonError.txt](https://github.com/nanoporetech/bonito/files/12113226/bonitoCythonError.txt)

I've tried doing no-cache installs and changing the gcc version, to no avail.

**Comment by juanjo255** [comment]
Hello, I got the same problem. The problem with remora was solved (see [](https://github.com/nanoporetech/remora/issues/95)). While another version of bonito is released, you can clone the repository and manually change the remora version (ont-remora==2.1.3) in requirements.txt for installation.

Regards.

**Comment by bettingr** [comment]
I tried this and got a dependency version problem.  ont-bonito 0.7.1 wants pod5 at 0.1.16, but ont-remora 2.1.3 wants pod5 > 0.2.  Plus, before that, I had to do a manual install of sympy, which I hadn't needed to do before.

**Comment by BioWu** [comment]
pip install Cython==0.29.36
pip install --no-build-isolation -e remora/ 

Please refer this: https://github.com/scikit-learn/scikit-learn/issues/26858

**Comment by bettingr** [comment]
@BioWu: thank you for the advice, that did not solve the problem.  It didn't clear up the compilation problems, and various tweaks still left the pod5 dependency mismatch as an issue.

Was the second pip supposed to be run from a downloaded ont-remora?  The "-e" and slash after `remora/` seemed to suggest that.

**Comment by tdido** [comment]
In case it's useful, I was able to get a working installation from source with these commands:

```bash
mamba create -y -n bonito pip python=3.9
conda activate bonito
git clone git@github.com:nanoporetech/bonito.git
git clone git@github.com:nanoporetech/remora.git
sed -i 's/cython/cython==0.29.36/' remora/setup.py # pin cython to latest 0.29
pip install -e remora
pip install -e bonito
```

**Comment by rob234king** [comment]
The master branch should be fixed and we will update pypi as soon ass we can.

**Comment by iiSeymour** [comment]
[v0.7.2](https://github.com/nanoporetech/bonito/releases/tag/v0.7.2) is now available from [PyPI](https://pypi.org/project/ont-bonito/0.7.2/).
